export const LOGIN_PROFILE_REQUEST = 'LOGIN_PROFILE_REQUEST';
export const LOGIN_PROFILE_FAILURE = 'LOGIN_PROFILE_FAILURE';
export const LOGIN_PROFILE_SUCCESS = 'LOGIN_PROFILE_SUCCESS';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

export const GET_SELLERS_REQUEST = 'GET_SELLERS_REQUEST';
export const GET_SELLERS_FAILURE = 'GET_SELLERS_FAILURE';
export const GET_SELLERS_SUCCESS = 'GET_SELLERS_SUCCESS';

export const SELECT_STORE = 'SELECT_STORE';

export const GET_CART_DETAIL_REQUEST = 'GET_CART_DETAIL_REQUEST';
export const GET_CART_DETAIL_FAILURE = 'GET_CART_DETAIL_FAILURE';
export const GET_CART_DETAIL_SUCCESS = 'GET_CART_DETAIL_SUCCESS';

export const UPDATE_CART_TO_SERVER_REQUEST = 'UPDATE_CART_TO_SERVER_REQUEST';
export const UPDATE_CART_TO_SERVER_FAILURE = 'UPDATE_CART_TO_SERVER_FAILURE';

export const ADD_NEW_PRODUCT_TO_CART = 'ADD_NEW_PRODUCT_TO_CART';

export const CHANGE_PRODUCT_QUANTITY_IN_CART =
  'CHANGE_PRODUCT_QUANTITY_IN_CART';
